ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/step_counter
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/bma4xy
obj-y	:=  bma4xy_stc.o


